# Generated by Django 4.0.3 on 2022-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='secu',
            field=models.BigIntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
