# Generated by Django 4.0.3 on 2022-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_alter_personnel_secu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='secu',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
