# Generated by Django 4.0.3 on 2022-06-13 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0015_remove_machine_id_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 8, 6, 21, 13286)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=6),
        ),
    ]
