# Generated by Django 4.0.3 on 2022-06-13 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0020_remove_personnel_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='lieu',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 8, 9, 11, 214522)),
        ),
    ]
